name: debug
on:
  push:
    branches:
      - debug
jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: build debug code image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ehco1996/django-sspanel
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "debug"
          dockerfile: deploy/Dockerfile.DEBUG-CODE
